{
    "type": "bundle",
    "id": "bundle--8e956d6d-1737-4b8a-bd48-585edaad17e0",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--35b5a9ee-f29e-4114-ab96-5a7eef01a20f",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2022-01-29T00:27:50.346808Z",
            "modified": "2022-01-29T00:27:50.346808Z",
            "name": "CVE-2022-23097",
            "description": "An issue was discovered in the DNS proxy in Connman through 1.40. forward_dns_reply mishandles a strnlen call, leading to an out-of-bounds read.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2022-23097"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}