{
    "type": "bundle",
    "id": "bundle--12b1fabe-4b0d-4a78-9f76-4e5069edb7c0",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--ee72f3f0-dea3-4c11-933c-d7b22ef13f0d",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2022-09-17T00:58:51.759246Z",
            "modified": "2022-09-17T00:58:51.759246Z",
            "name": "CVE-2022-36002",
            "description": "TensorFlow is an open source platform for machine learning. When `Unbatch` receives a nonscalar input `id`, it gives a `CHECK` fail that can trigger a denial of service attack. We have patched the issue in GitHub commit 4419d10d576adefa36b0e0a9425d2569f7c0189f. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2022-36002"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}