{
    "type": "bundle",
    "id": "bundle--a5a38b44-04e2-4202-8ee2-12d9811866a3",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--c0400062-5c9f-478f-adc4-e72ff5b42b79",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2022-01-22T00:28:13.552938Z",
            "modified": "2022-01-22T00:28:13.552938Z",
            "name": "CVE-2022-0319",
            "description": "Out-of-bounds Read in Conda vim prior to 8.2.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2022-0319"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}